site_name: mkdocs-jupyterlite
site_url: https://nickcrews.github.io/mkdocs-jupyterlite/
repo_url: https://github.com/nickcrews/mkdocs-jupyterlite/

nav:
  - Home: index.md
  - Notebook 1: notebook.ipynb

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

plugins:
  - jupyterlite:
      enabled: true
      notebook_patterns:
        - '*.ipynb'